"""mejoras

Revision ID: a0d3fe0b71ed
Revises: 2bc3e80f46f0
Create Date: 2024-09-25 11:01:05.203251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0d3fe0b71ed'
down_revision = '2bc3e80f46f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('ruc', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sectores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('empleados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_sector', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('nombre', sa.String(length=100), nullable=False))
        batch_op.create_foreign_key(None, 'sectores', ['id_sector'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empleados', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('nombre')
        batch_op.drop_column('id_sector')

    op.drop_table('sectores')
    op.drop_table('empresa')
    # ### end Alembic commands ###
