"""Descripción de la migración

Revision ID: b4ffbce744da
Revises: dff667ec8484
Create Date: 2024-09-25 13:24:31.682384

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b4ffbce744da'
down_revision = 'dff667ec8484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empleados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_sector', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.Column('ciudad', sa.String(length=100), nullable=False),
    sa.Column('salario', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_sector'], ['sectores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('empleado')
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ruc', sa.BIGINT(), nullable=False))
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('sectores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_empresa', sa.Integer(), nullable=False))
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.create_foreign_key(None, 'empresa', ['id_empresa'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sectores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('id_empresa')

    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('ruc')

    op.create_table('empleado',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('edad', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ciudad', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('salario', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('empleados')
    # ### end Alembic commands ###
